Repository kieler/klighd-vscode, pull requests merged in 2022-07, with the labels that each got.

#96 Show a default selection style if none is defined.
  packages/klighd-core/src/skgraph-models.ts
  packages/klighd-core/src/views-common.ts
  packages/klighd-core/src/views-rendering.tsx
  packages/klighd-core/src/views-styles.tsx
Labels: enhancement, klighd-core

#95 fix: interactive: do not intentionally update the diagram if nothing changed.
  packages/klighd-interactive/src/klighd-interactive-mouselistener.ts
Labels: bug

#110 Render option documentation and quick action persistence
  packages/klighd-core/src/di.config.ts
  packages/klighd-core/src/options/general-panel.tsx
  packages/klighd-core/src/options/option-models.ts
  packages/klighd-core/src/options/options-renderer.tsx
  packages/klighd-core/src/options/render-options-registry.ts
  packages/klighd-core/src/sidebar/sidebar-panel-registry.ts
  packages/klighd-core/src/sidebar/sidebar.tsx
  packages/klighd-core/src/views-rendering.tsx
  packages/klighd-core/styles/sidebar.css
Labels: enhancement
