Repository kieler/klighd-vscode, pull requests merged in 2023-03, with the labels that each got.

#128 Unit testing framework
  .github/workflows/ci.yml
  .vscode/launch.json
  package.json
  packages/klighd-core/src/diagram-pieces/diagram-piece-request-manager.ts
  packages/klighd-core/test/diagram-pieces/diagram-piece-request-manager.test.ts
  tsconfig.json
  yarn.lock
Labels: enhancement

#129 core: fixes overlayed titles sometimes having an unexpected offset.
  packages/klighd-core/src/depth-map.ts
  packages/klighd-core/src/skgraph-model-renderer.ts
  packages/klighd-core/src/titles/title-storage.ts
  packages/klighd-core/src/views-common.ts
  packages/klighd-core/src/views-rendering.tsx
  packages/klighd-core/src/views.tsx
Labels: bug, klighd-core

#130 child placement and rendering bounding box fixes
  packages/klighd-core/src/views-common.ts
  packages/klighd-core/src/views-rendering.tsx
Labels: bug, klighd-core

#131 Build fixes for Windows
  applications/klighd-cli/package.json
  applications/klighd-cli/server/version.ts
  applications/klighd-vscode/package.json
  packages/klighd-core/package.json
  packages/klighd-interactive/package.json
  yarn.lock
Labels: bug

#132 Fix style propagation and order of style handling.
  packages/klighd-core/src/views-common.ts
  packages/klighd-core/src/views-rendering.tsx
  packages/klighd-core/src/views-styles.tsx
  packages/klighd-core/src/views.tsx
Labels: bug
